version: 2.1
orbs:
  newman: postman/newman@0.0.2
jobs:
  newman-collection-run:
    executor: newman/postman-newman-docker
    steps:
      - checkout
      - newman/newman-run:
          collection: ./Project.postman_collection.json
          environment: ./Testing3.postman_environment.json
  newman-collection-run2:
    executor: newman/postman-newman-docker
    steps:
      - checkout
      - newman/newman-run:
          collection: ./File_Export_Import.postman_collection.json
          environment: ./Testing3.postman_environment.json
workflows:
  version: 2
  workflow:
    jobs:
    - newman-collection-run:
         filters:
             branches:
                only:
                  - Test
    - newman-collection-run2:
         filters:
             branches:
                only:
                  - Test
